### ISSUE TITLE
ETD ion notation - z' series

### ISSUE THREAD

**Issue by tcolby-koeln** [EMSL-Computing/PSpecteR#1]
Hi Folks,
Very useful tool, many thanks for the development.
But there's a shortcoming that I've noticed when looking at ETD spectra, namely that the spectra seldom contain native z ions, so one sees no annotations from the peptide c-terminus.
It's usually the z' ion series is most intense, but these can't be annotated, unless I'm overlooking something. One can add a c-term mass difference to get them annotated, but that gets complicated when one is modelling other mods as well.

Could you either expand the set of available ions for annotation (so that one can also select z' and z", for example), or simply replace z with z'? Or have I missed a feature?

Thanks

**Comment by David-Degnan** [comment]
Thank you for using PSpecteR and taking the time to suggest a way to improve our tool. We currently don't have z' (z+1, or the z ion plus a Hydrogen) added to PSpecteR. We will implement both z' and z'' into PSpecteR as optional fragment types.

**Comment by David-Degnan** [comment]
Good afternoon @tcolby-koeln! After thinking about this request, we have decided to include the ability to modify a-c and x-z ions by a mass change. Check out the "Modify Ions" button in 2. Scan & XIC in PSpecteR:1.0.1 at https://hub.docker.com/repository/docker/emslcomputing/pspecter
