### ISSUE TITLE
Manual Modification search: Add mass --> calculate hangs up

### ISSUE THREAD

**Issue by tcolby-koeln** [EMSL-Computing/PSpecteR#2]
With the new version of pspectr 1.0.1 - with the manage ions option, I can't get the "add mass" feature to work in the Manual Modification search. Initially my spectrum is annotated, but as soon as I try to add a mass to a particular residue and press "calculate", the panel greys out and doesn't return to the spectrum view.
Is this feature now somehow incompatible with the manage ions mass addition?

**Comment by David-Degnan** [comment]
Good catch. Issue fixed. Latest versions pushed to Github and Dockerhub. Let me know if you run into any other bugs.

Thanks!
